### ISSUE TITLE
PR for Wiki: Some clarifications to "How to create a cool plugin" tutorial

### ISSUE THREAD

**Issue by sketch34** [AutodeskGames/stingray-plugin#8]
Hi @jschmidt42, thanks so much for a very awesome and fun tutorial! It's so great how you designed it to touch on all the important aspects of plugins, even external lib integration. Really good.

I've made a few clarifications in the tutorial wiki page to help others in the future, changes are to `How-to-create-a-cool-plugin.md`. You should be able to pull them into this wiki from here:
https://github.com/sketch34/stingray-plugin.wiki.git

I'm following this approach to propose a change to the Wiki from my fork back to here. Let me know if there is a better way:
https://stackoverflow.com/a/11481887/988870
https://stackoverflow.com/a/33828142/988870

Forked wiki viewable here: https://github.com/sketch34/stingray-plugin/wiki/How-to-create-a-cool-plugin

**Comment by jschmidt42** [comment]
@sketch34 I cannot access https://github.com/sketch34/stingray-plugin.wiki.git. Maybe you need to add more as a collaborator? You can also generate a `.patch` if you want. Thanks.

**Comment by jschmidt42** [comment]
@sketch34 I was able to get the changes. I will apply them. Thank you.

**Comment by jschmidt42** [comment]
commit d95e07ebb382ed97a6543fe168fa82ab958a5b29
Author: Jonathan Schmidt <jschmidt42@gmail.com>
Date:   Fri Jun 30 21:05:05 2017 -0400

    Clarifications proposed by @sketch34 at https://github.com/AutodeskGames/stingray-plugin/issues/8
