### ISSUE TITLE
Wiki update from @t_turcm 

### ISSUE THREAD

**Issue by sketch34** [AutodeskGames/stingray-plugin#9]
Hi Jonathan, a minor update to the wiki from @t_turcm after he went through the tutorial. I made a patch for you this time.

https://dl.dropboxusercontent.com/u/17430727/0001-Wiki-changes-from-t_turcm-Martin-Turcotte.patch

Thanks again for a great tutorial.

**Comment by jschmidt42** [comment]
@sketch34 I applied the patch. Let me know if everything is alright.
Thank you
